name: Docker Image CI

on:
  push:
    branches: [ Production ]
  pull_request:
    branches: [ Production ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d
    - name: Add remote origin
      run : |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: fetch
      run: |
        git fetch --all --unshallow
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:main -f
